### ISSUE TITLE
API changes

### ISSUE THREAD

**Issue by ollpu** [H4m5t3r/cses-cli#14]
Leave API change ideas here (comment or edit)

 - [x] REST-like URLs
   - Use plural on `courses`, `tasks`, etc
   - `submit` -> `submissions`
 - [x] Ping as GET-parameter
   - `/ping` -> `?ping=true`
   - Optional. False when omitted.
 - [x] Test time can be null
   - This can happen in TLE, (RTE?) and when test has not been run at all.
 - [x] Submission result progress as amount of tests completed (optional)
   - Separate from individual test results, because that is not always available

**Comment by anttoh** [comment]
Tests time could be null, if the test didn't finish.
